import Head from 'next/head';
import { useEffect, useState } from 'react';
import { Inter } from 'next/font/google';
import styles from '@/styles/Profile.module.css';
import { useRouter } from 'next/router';
import { SERVER_BASE_URL } from '@/js/Config';
import AppBar from '@/js/AppBar';
import BottomNavBar from '@/js/BottomNavBar';
import UserPanel from '@/js/UserPanel';
import MatchItemMobile from '@/js/MatchItemMobile';
import ProfileStatsPanel from '@/js/ProfileStatsPanel';
import ProfileMatchesPanel from '@/js/ProfileMatchesPanel';
const inter = Inter({ subsets: ['latin'] });
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';

export async function getServerSideProps(context) {
    const { params } = context;
    const { id } = params;
    const { query } = context;
    const globalPage = query.page ? Number(query.page) : 1;
    const { locale } = context;

    const requestOptions = {
        method: 'GET',
        headers: {
            'Content-Type': 'application/json',
        },
    };

    const user = await fetch(`${SERVER_BASE_URL}/api/v1/user?user_id=${id}`, requestOptions)
        .then(response => {
            if (response.status === 200) return response.json();
            return null;
        });

    const initialPredicts = await fetch(`${SERVER_BASE_URL}/api/v1/user/predicts?page=${globalPage}&user_id=${user.id}&league_id=${-1}`, {
        method: 'GET',
        headers: {},
    }).then(response => response.json());

    return {
        props: {
            user,
            globalPage,
            initialPredicts,
            ...(await serverSideTranslations(locale)),
        },
    };
}


export default function Home({ user, stats, globalPage, initialPredicts }) {
    const router = useRouter();
    const [predicts, setPredicts] = useState(initialPredicts.predicts);
  
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={`${styles.main} ${inter.className}`}>
                <AppBar title="el Torneo" />
                <UserPanel user={user} />
                <div className={styles.padding}>
                    <ProfileStatsPanel stats={initialPredicts} />
                    <ProfileMatchesPanel isMe={false} router={router} globalPage={globalPage} user={user} predicts={predicts} setPredicts={setPredicts} totalPredicts={initialPredicts.allPredicts} />
                </div>
                <BottomNavBar router={router} />
            </main>
        </>
    );
}
