import Head from 'next/head';
import { useEffect, useState } from 'react';
import { Inter } from 'next/font/google';
import styles from '@/styles/Calendar.module.css';
import { useRouter } from 'next/router';
import { SERVER_BASE_URL } from '@/js/Config';
import AppBar from '@/js/AppBar';
import LeaguesPanel from '@/js/LeaguesPanel';
import Switch from '@/js/Switch';
import HomeMatchesPanel from '@/js/HomeMatchesPanel';
import BottomNavBar, { EPAGE_CAL } from '@/js/BottomNavBar';
import moment from 'moment';
import Calendar from '@/js/Calendar';
import MatchItemMobile from '@/js/MatchItemMobile';
const inter = Inter({ subsets: ['latin'] });
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { useTranslation } from 'next-i18next';
import { UAParser } from 'ua-parser-js';

export async function getServerSideProps(context) {
  const { query } = context;
  const timestamp = query.date ? Number(query.date) : new Date(moment().format('YYYY-MM-DD')).getTime();
  const { locale } = context;

  const {req} = context
  const token = req.cookies.token;

  let isAndroid = false;
  let isIOS = false
  {
      const userAgent = context.req.headers['user-agent'];
      const parser = new UAParser(userAgent);
      const uaResult = parser.getResult();
      const osName = uaResult.os.name || 'Unknown';
      isAndroid = osName == 'Android'
      isIOS = osName == 'iOS'
  }

  const url = `${SERVER_BASE_URL}/api/v1/matches/day?timestamp=${timestamp}&lang=en`
  const matches = await fetch(url, {
    method: 'GET',
    headers: { 'Content-Type': 'application/json',
       'Authentication': token ? token : ''
     },
  })
    .then(response => response.json())

  return {
    props: {
      matches: matches,
      isAndroid,
      isIOS,
      date: moment(timestamp).format('YYYY-MM-DD'),
      ...(await serverSideTranslations(locale)),
    },
  };
}

export default function Home({isAndroid, isIOS,  matches, date }) {
  const {t} = useTranslation()
  const router = useRouter()
  let currentLeague = null

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <AppBar title={'el Torneo'} />
        <div className={styles.calendar_panel}>
          <div className={styles.date_cont}>
            <img className={styles.cal_icon} src={`${SERVER_BASE_URL}/data/icons/calendar_black.svg`} />
            <span className={styles.date}>{moment(date).format('DD')} {t(moment(date).format('MMM').toLowerCase())} {moment(date).format('YYYY')}</span>

          </div>
          <Calendar router={router} date={date} />
        </div>

        <div className={styles.matches_cont}>

          {matches.map((m, i) => {

            let renderLeague = false;
            if (!currentLeague || currentLeague != m.league_name) {
              currentLeague = m.league_name
              renderLeague = true;
            }

            return <div key={`match_${m.id}`}>
              {renderLeague ? <div className={`${styles.league_cont} ${i === 0 ? styles.mt_0 : ''}`} >
                <img className={styles.league_icon} src={`${SERVER_BASE_URL}/data/leagues/${m.league_name}_colored.png`} />
                <div className={styles.league_name_cont}>
                  <span className={styles.league_name}>{m.league_name}</span>
                  <span className={styles.league_week}>Matchday {m.week}</span>
                </div>
              </div> : null}
              <MatchItemMobile currentWeek={m.currentWeek} router={router} match={m} />
            </div>
          })}

          {!matches.length ? <span className={styles.no_matches}>There are no matches.</span> : null}
        </div>
        <BottomNavBar isAndroid={isAndroid} isIOS={isIOS} router={router} page={EPAGE_CAL} />
      </main>
    </>
  );
}
